linters:
  - eslint
  - prettier
  - markdown
  - json
  - yamllint
  - shellcheck
  - ansible-lint
  - terraform
  - dockerfile
  - hadolint

global:
  ignore:
    - "**/.github/workflows/integration.yml"
