version: "3.9"

services:
  todo:
    image: "${TESTING_IMAGE}"
#    ports:
#      - "80:80"
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./healthchecks:/healthchecks
    healthcheck:
      test: /healthchecks/postgres-healthcheck
      interval: "5s"
  service1:
    image: "${TESTING_IMAGE}"
    depends_on:
      todo:
        condition: service_started
      postgres:
        condition: service_started  # TODO maybe change to "condition: service_healthy"
    command: curl --fail http://todo:80 || exit 1
#    ports:
#      - "5000:5000"
