name: Feature Request
description: File a feature request
title: "[Feature Request]: "
labels: ["enhancement", "triage"]
assignees:
  - JakubSzuber
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: feature-idea
    attributes:
      label: What you want to be implemented in the future?
      description: Also tell us, what you want to be implemented, improved, or changed in our project. Describe the idea, tell us why you want the change, and if you have any tips on how to bring that idea to life feel free to give hints!
      placeholder: "Make a feature that..."
    validations:
      required: true
  - type: dropdown
    id: idea-type
    attributes:
      label: Type of idea
      description: To which aspect of the repository the idea is related?
      multiple: true
      options:
        - General idea
        - Source code
        - AWS infrastructure
        - GHA pipeline
        - Other
    validations:
      required: false
