---
apiVersion: v1
kind: Service
metadata:
    name: {{ .Values.appName }}
    namespace: {{ .Values.namespace }}
    labels:
    #     app: {{ .Values.appName }}
    # annotations:
    #     service.beta.kubernetes.io/aws-load-balancer-type: "elb"
spec:
    ports:
      - protocol: TCP
        port: 80
        targetPort: 80
    selector:
        app: {{ .Values.appName }}
    type: LoadBalancer
