---
apiVersion: v1
kind: Service
metadata:
  annotations:
    alb.ingress.kubernetes.io/backend-protocol-version: HTTP2 #This tells AWS to send traffic from the ALB using HTTP2. Can use GRPC as well if you want to leverage GRPC specific features
  labels:
    app: {{ .Values.appName }}
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: "80"
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: {{ .Values.appName }}
  sessionAffinity: None
  type: NodePort


# ---
# apiVersion: v1
# kind: Service
# metadata:
#     name: {{ .Values.appName }}
#     namespace: {{ .Values.namespace }}
#     labels:
#         app: {{ .Values.appName }}
#     # annotations:
#     #     service.beta.kubernetes.io/aws-load-balancer-type: "elb"
# spec:
#     ports:
#       - protocol: TCP
#         port: 80
#         targetPort: 8080
#     selector:
#         app: {{ .Values.appName }}
#     type: LoadBalancer
