---

# TODO Description of the workflow

name: CI

onbreakfornow:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Run Super-Linter
      uses: github/super-linter@v4
      env:
        VALIDATE_ALL_CODEBASE: false
        DEFAULT_BRANCH: master
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-push-docker:  # This job could be executed through the ubuntu, windows, and macOS hosted runners but it require additional changes
#    runs-on: ${{ matrix.os }}
#    strategy:
#      matrix:
#        os: [ubuntu-latest, windows-latest, macOS-latest]
    runs-on: ubuntu-22.04
    steps:
# TODO do below part after choosing the language
#     - name: Get the source code
#       uses: actions/checkout@v3

#     - name: Python Setup
#       uses: actions/setup-python@v4
#       with:
#         python-version: '3.9'
#         cache: 'pip' # caching pip dependencies

#     - run: pip install -r requirements.txt

#todo not sure about this part
#    - name: Run unit tests
#      run: |
#        python -m unittest discover tests/


    # TODO below action won't be required if you finishe the above part
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # TODO unit tests - make separate job for it and if it's possible run it in parallel
    
    # TODO integration tests (probably with docker compose) - make separate job for it and if it's possible run it in parallel

    # TODO CVE scanning (Snyk, Trivy, AWS CodeGuru) - make separate job for it and if it's possible run it in parallel

    # TODO maybe you should put somewhere else those part
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker image and push it if the event is direct push or merged pull request
      uses: docker/build-push-action@v4
      with:
        push: ${{ github.event_name != 'pull_request' }}
        tags: jakubszuber/testing_image:latest,jakubszuber/testing_image:1.01
        cache-from: type=gha  # Use cached image layers to reduce image building time
        cache-to: type=gha,mode=max
