name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:  # This job could be executed through the ubuntu-latest, windows-latest, and macOS-latest hosted runners but it require additional changes
#    runs-on: ${{ matrix.os }}
#    strategy:
#      matrix:
#        os: [ubuntu-latest, windows-latest, macOS-latest]
    runs-on: ubuntu-22.04

    steps:
    - name: Get the source code
      uses: actions/checkout@v3

    - name: Python Setup
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip' # caching pip dependencies

    - run: pip install -r requirements.txt

    # TODO tests

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Docker build
      uses: docker/build-push-action@v4
      with:
        push: ${{ github.event_name != 'pull_request' }}
        tags: jakubszuber/testing_image:latest,jakubszuber/testing_image:1.01
