name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
#   build:  # This job will be executed through the ubuntu-latest, windows-latest, and macOS-latest hosted runners
#     runs-on: ${{ matrix.os }}
#     strategy:
#       matrix:
#         os: [ubuntu-latest, windows-latest, macOS-latest]

#     steps:
#     - uses: actions/checkout@v2

#     - name: Set up JDK 1.8
#       uses: actions/setup-java@v1
#       with:
#         java-version: 1.8

#     - name: Grant execute permission for gradlew
#       run: chmod +x gradlew

#     - name: Build with Gradle
#       run: ./gradlew build

#     - name: Build and Push Docker Image
#       uses: mr-smithers-excellent/docker-build-push@v4  # Use community-created Action (that in the background builds a Docker image based on the source code and then pushes it to the Docker Hub as the specified image's tag)
#       with:
#         image: jakubszuber/testing_image:1.01
#         registry: docker.io
#         username: ${{ secrets.DOCKER_USERNAME }}
#         password: ${{ secrets.DOCKER_PASSWORD }}

  build-image:
#   depends: build
    name: Build Image
    runs-on: ubuntu-latest
    steps:
            
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Docker build
        uses: docker/build-push-action@v4
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: jakubszuber/testing_image:latest,jakubszuber/testing_image:1.01
        
