name: Features

on: [workflow_dispatch]

jobs:
  build:
    continue-on-error: true  # Every step in this job will be treated in our workflow as it is successful even if it's not (so the execution of next jobs won't be interupted by this job and in GHA GUI we will always see the green check mark for this job (but not necessarily for the step/s))
    strategy:
      matrix:  # The current job will be executed multiple time (6 times because it's a number of possible combinations of matrix values (6) plus additional job definied in "include:" and minus the specified combination from the pool of the combinations definied in "exclude:") in parallel and every job will have different combinations on matrix values e.g. there will be job that will run on ubuntu-latest and will install 12 node version, windows-latest and will install 12 node version, and so on. Btw. all of this "kinds" of workflows will be displayed witin the single job "build" in GHA GUI
        node-version: [12, 14, 16]
        operating-system: [ubuntu-latest, windows-latest]
        include:
          - node-version: 18
            operating-system: ubuntu-latest
            BOOL: 'true'
        exclude:
          - node-version: 12
            operating-system: windows-latest
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm ci
#       - name: Build project
#         run: npm run build
      - name: Print the communicate if the job have a BOOL variable
        run: test ${{ matrix.$BOOL }} = 'true' && echo "I have a boolean value with true values"
